### ISSUE TITLE
requires grunt-contrib/tasks/helpers.js ?

### ISSUE THREAD

**Issue by zackd** [richardbutler/node-spritesheet#1]
hi there, stumbled for moment when i got a warning after installing node-spritesheet and running the grunt task:

`<WARN> Helper "options" not found. Use --force to continue. </WARN>`

..but noticed that the missing helpers were part of grunt-contrib, copied https://github.com/gruntjs/grunt-contrib/blob/master/tasks/helpers.js to ~/.grunt/tasks/ re- initialised my app (grunt init) all all works as expected :)

is it possible to add this as a dependency ?

**Comment by rubenstolk** [comment]
Yes please!!!

**Comment by richardbutler** [comment]
Apologies, I hadn't realised as I use grunt-contrib in all my projects. I'll take a look at removing the dependency within the task as it seems silly to need it.

**Comment by richardbutler** [comment]
grunt-contrib is required by the project's own grunt build process (brainmelt), so it's now in as a hard dependency. This shouldn't cause any more problems, hopefully.

**Comment by zackd** [comment]
awesome :)

**Comment by rubenstolk** [comment]
Please also update npm!

On Wed, Sep 19, 2012 at 8:43 PM, zack notifications@github.com wrote:

> awesome :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richardbutler/node-spritesheet/issues/1#issuecomment-8694167.

## 

Ruben Stolk

CHANGER, _Raising the bar in Online Experience!_

+91 95 6105 0034
+31 6 46 11 80 37

INDIA OFFICE
3rd Floor, C-1 Building, Nyati Millennium, Viman Nagar, Pune – 411014,
India (http://g.co/maps/g9y7n)
http://changer.in

NETHERLANDS OFFICE
Vlietweg 17-V, NL-2266 KA,  Leidschendam, Netherlands (
http://g.co/maps/tcpwn)
+31 88 1001300 - http://changer.nl

**Comment by richardbutler** [comment]
Oh yeah! Done - 0.2.0

Sorry, this is my only NPM package - it's not a habit for me. :)

**Comment by rubenstolk** [comment]
Hey Richard,

thanks so much for your efforts, there is still one issue,
grunt-contrib-lib is a separate module which you require but is not in
package.json. This breaks the module. Could you fix this!?

Thanks Ruben

On Wed, Sep 19, 2012 at 9:16 PM, Richard Butler notifications@github.comwrote:

> Oh yeah! Done - 0.2.0
> 
> Sorry, this is my only NPM package - it's not a habit for me. :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richardbutler/node-spritesheet/issues/1#issuecomment-8695412.

## 

Ruben Stolk

CHANGER, _Raising the bar in Online Experience!_

+91 95 6105 0034
+31 6 46 11 80 37

INDIA OFFICE
3rd Floor, C-1 Building, Nyati Millennium, Viman Nagar, Pune – 411014,
India (http://g.co/maps/g9y7n)
http://changer.in

NETHERLANDS OFFICE
Vlietweg 17-V, NL-2266 KA,  Leidschendam, Netherlands (
http://g.co/maps/tcpwn)
+31 88 1001300 - http://changer.nl

**Comment by richardbutler** [comment]
Damn, I'll get the hang of this stuff eventually. That was where the offending helper was - fixed in 0.2.1 on NPM.

**Comment by rubenstolk** [comment]
Thanks!

On Thu, Sep 20, 2012 at 1:14 PM, Richard Butler notifications@github.comwrote:

> Damn, I'll get the hang of this stuff eventually. That was where the
> offending helper was - fixed in 0.2.1 on NPM.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/richardbutler/node-spritesheet/issues/1#issuecomment-8719129.

## 

Ruben Stolk

CHANGER, _Raising the bar in Online Experience!_

+91 95 6105 0034
+31 6 46 11 80 37

INDIA OFFICE
3rd Floor, C-1 Building, Nyati Millennium, Viman Nagar, Pune – 411014,
India (http://g.co/maps/g9y7n)
http://changer.in

NETHERLANDS OFFICE
Vlietweg 17-V, NL-2266 KA,  Leidschendam, Netherlands (
http://g.co/maps/tcpwn)
+31 88 1001300 - http://changer.nl
