### ISSUE TITLE
Add less-support

### ISSUE THREAD

**Issue by rubenstolk** [richardbutler/node-spritesheet#14]
Without retina-support, outputting to .less is compatible, however this doesn't work with retina-support correctly because of different handling of media-queries.

Any plan of adding support?

**Comment by rubenstolk** [comment]
Actually,

there only has to be one media-query:

@media (-webkit-min-device-pixel-ratio: 2) {
  .sprite {
    background-image: url( 'sprite@2x.png' );
    background-size: 980px 800px;
  }
}

where you need to generate the background-size of course...

**Comment by richardbutler** [comment]
No plan to include it, no. It would work with SASS out of the box, but that's not the answer you were looking for.

Happy to consider a pull request if you find a nice way of supporting it.
