### ISSUE TITLE
Still being maintained? & Grunt 0.4 support?

### ISSUE THREAD

**Issue by duro** [richardbutler/node-spritesheet#15]
Richard,

Are you still maintaining the project? Seems it's been a few months since a commit, and now Grunt 0.4 is very much upon us, so I'm wondering when the library will be ported over to support 0.4.

It would be a shame if this project fell by the wayside.

**Comment by richardbutler** [comment]
Should work on 0.4 now. I haven't _tested_ it, as I don't use 0.4 on any projects yet.
