### ISSUE TITLE
HiDPI CSS numbers are wrong

### ISSUE THREAD

**Issue by chearon** [richardbutler/node-spritesheet#17]
Hi Richard, glad to see you're back.  Months ago you made spritesheet support retina displays, but there were some small mistakes that never got resolved.

Basically, on Retina devices, the images were simply showing up as twice the size.  To achieve the high density effect the image is supposed to have the same `width` and `height` but a different `background-size`.  I'm not sure these diffs are still compatible with your repo so I'm just going to reference them rather than pull request.

I've been using these patches for the past 3 months and it works wonderfully on both Android (1.5) and Retina displays, as well as legacy.

Consistent `width` and `height`, scaled `background-size`: cd3156a9370ca98dfbcb6adb68964af49f541e38
Update `background-position`: 2034f4badeb76491ceb854b8286f44a9f79a2981

**Comment by mente** [comment]
+1 for this update. Without background-size retina support is useless. Any help needed to get this update in upstream?

**Comment by chearon** [comment]
You'll have to apply the diffs yourself (or pull from me) they're not in this repository.  Not sure what happened with the GitHub links, they're my commits but somehow they're being shown as in this repository...

**Comment by mente** [comment]
Yeap, found out it's already. In my app it will be difficult to use custom npm module. Have to wait till it's got into upstream.

**Comment by mente** [comment]
Why don't you make PR?

**Comment by chearon** [comment]
Because I applied some patches to make the `selector` option more intelligent, but they didn't get accepted so I'm not sure how compatible it is.  I'm looking into that now though...

**Comment by mente** [comment]
Found a [way](http://debuggable.com/posts/how-to-fork-patch-npm-modules:4e2eb9f3-e584-44be-b1a9-3db7cbdd56cb) to use forked module. Giving a try to your fork :)

**Comment by chearon** [comment]
Nice, let me know if you have any issues, I'm going to create a separate pull request like I should've in the first place.

**Comment by mente** [comment]
I think there's no need to write background-size for non-retina part of css

**Comment by chearon** [comment]
That's true, but it'd make the code less elegant, and old browsers that don't support it would simply ignore it

**Comment by richardbutler** [comment]
Fixed, but agree there probably isn't a need to add background size at all, maybe overkill. Any use case where simply `background-position` wouldn't suffice? Probably not.

**Comment by mente** [comment]
`background-size` is more compact for retina than specifying `background-position` for each sprite.

**Comment by richardbutler** [comment]
@mente Good call. I hadn't realised just how much CSS could actually be saved doing it that way.
