### ISSUE TITLE
Generated sprites are not always the same for 2x/1x

### ISSUE THREAD

**Issue by lrvick** [richardbutler/node-spritesheet#25]
These were both generated from the same source images:

1x: http://i.imgur.com/rtTRyLn.png

2x: http://i.imgur.com/evtPRcs.png

As you can see, the bottom 5 icons shift, and thus are also wrong when rendered in the browser with the 1x background offset values.

Not totally sure why this is happening...

It seems like the 1x and 2x versions are generated independently.  Perhaps a better approach might be to generate the 2x version, then generate the 1x version from the 2x version. That way ratios/positions are always guaranteed to be preserved.

**Comment by richardbutler** [comment]
That's bizarre and something up with the underlying algorithm (gulp). Have you managed to find a workaround since?

**Comment by lrvick** [comment]
The only workaround I have is to only generate a 2x version, then manually use grunt-imagemagick to downsample that one to make a 1x version. A dirty hack at best.

**Comment by stefanoortisi** [comment]
I'm having this issue too. Perhaps the best would be do not rely on imagemagick to create the spritesheet. Asking the user to install a third part software is kind of lame.

**Comment by stefanoortisi** [comment]
@lrvick can you please explain me better how did you manage to do this workaround?
If I try to generate the 2x version first, i'm gonna have a wrong css with all the sprite elements double sized, isn't it? How can you get the right css then?

Cheers

**Comment by ieatfood** [comment]
I have ran into this as well and narrowed it down to not having even pixel dimensions for the 2x image. Once I rounded the dimensions the issue went away.
