### ISSUE TITLE
Exporting png and css to different directories

### ISSUE THREAD

**Issue by duro** [richardbutler/node-spritesheet#3]
In order to maintain my projects folder structure it would be nice if I could export the css and spritesheet png to different folders. Any chance that may be in the works?

**Comment by richardbutler** [comment]
I hadn't given it much thought as this project was only a quick stab, but I'll have a look into adding it if it's useful. For the time being, as a workaround, you could output to a temp folder then use grunt-contrib's copy task to copy them to separate folders.

**Comment by duro** [comment]
The only problem with this is it still requires a manual update to the
spritesheet path. Since I'm already doing that, doing th copy manually is
not a big deal either.

However, don't abandon this project. There are currently no other good
solutions for creating spritesheets via a grunt task (that I am aware of),
and getting this one working would greatly help our project. Since this one
does not work with the latest version of Grunt we had to switch back to a
manual spritesheet creation process. I'd love to get this automated.

AD

**Comment by richardbutler** [comment]
@Duro - I've just pushed a fix, you should now be able to do this as per the updated README. Let me know if it lets you do what you want.

Thanks for the support - I originally put this together to scratch my own itch but it's nice to know it's helping someone else out too.
